#!/usr/bin/env bash
# Configure localhost and facebook.com resolution

cp /etc/hosts /tmp/hosts

sed 's/127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/' /tmp/hosts > /tmp/hosts.new

grep -q "facebook.com" /tmp/hosts.new &&
  sed -i 's/.*facebook.com/8.8.8.8 facebook.com/' /tmp/hosts.new ||
  echo "8.8.8.8 facebook.com" >> /tmp/hosts.new

cat /tmp/hosts.new > /etc/hosts
